version: '3.1'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_teste
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_fastapi_backend
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: db_fastapi_backend
      MARIADB_USER: root
      MARIADB_PASSWORD: root
      mysql -h localhost -P 3307 -u root -p

      
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
