"""nova coluna tamanhos

Revision ID: 6b5c4bfe4abd
Revises: 44f4e4564451
Create Date: 2024-06-17 09:51:56.487708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b5c4bfe4abd'
down_revision: Union[str, None] = '44f4e4564451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('tamanhos', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'tamanhos')
    # ### end Alembic commands ###
