"""nova coluna tamanho definidos 

Revision ID: c3157a9c669c
Revises: 6b5c4bfe4abd
Create Date: 2024-06-17 10:13:26.171222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3157a9c669c'
down_revision: Union[str, None] = '6b5c4bfe4abd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('tamanhos', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'tamanhos')
    # ### end Alembic commands ###
